// src/components/ProductCard.tsx
import { Show } from 'solid-js';
import { formatPrice } from '@/lib/utils';
import type { Product } from '@/types';

interface Props {
  product: Product;
}

export default function ProductCard(props: Props) {
  return (
    <a
      href={`/produto/${props.product.slug}`}
      class="card group"
    >
      {/* Imagem */}
      <div class="relative aspect-square overflow-hidden bg-gray-100">
        <Show
          when={props.product.main_image_url}
          fallback={
            <div class="w-full h-full flex items-center justify-center text-gray-400">
              Sem imagem
            </div>
          }
        >
          <img
            src={props.product.main_thumb_url || props.product.main_image_url!}
            alt={props.product.name}
            class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
            loading="lazy"
          />
        </Show>

        {/* Badge Destaque */}
        <Show when={props.product.featured}>
          <span class="absolute top-2 right-2 bg-primary-500 text-white text-xs font-bold px-2 py-1 rounded-full">
            Destaque
          </span>
        </Show>
      </div>

      {/* Info */}
      <div class="card-body">
        <h3 class="font-semibold text-lg text-gray-900 line-clamp-2 group-hover:text-primary-500 transition-colors">
          {props.product.name}
        </h3>

        <Show when={props.product.description}>
          <p class="text-sm text-gray-600 line-clamp-2 mt-1">
            {props.product.description}
          </p>
        </Show>

        <Show when={props.product.price > 0}>
          <div class="mt-3">
            <span class="text-xl font-bold text-primary-500">
              {formatPrice(props.product.price)}
            </span>
            <span class="text-sm text-gray-500 ml-1">/ un</span>
          </div>
        </Show>

        <button class="btn btn-primary w-full mt-4">
          Ver Detalhes
        </button>
      </div>
    </a>
  );
}

// src/features/catalog/components/ProductCard.tsx
// FILE: src/features/catalog/components/ProductCard.tsx
import { memo } from 'react'
import { ShoppingCart, Eye } from 'lucide-react'
import { optimizeUrl } from '../../../core/lib/cloudflare'
import type { Product } from '../../../types/product'

interface Props {
  product: Product
  onView: () => void
  onAdd: () => void
}

export default memo(function ProductCard({ product, onView, onAdd }: Props) {
  const imgId = product.thumb_url || product.imagem_url || product.variacoes?.[0]?.thumb_url || product.variacoes?.[0]?.imagem_url
  const imgUrl = imgId ? optimizeUrl(imgId, 'thumbnail') : ''
  
  return (
    <article className="group bg-white rounded-2xl overflow-hidden shadow-card hover:shadow-card-hover transition-all duration-300 transform hover:-translate-y-1">
      <div className="relative aspect-square overflow-hidden bg-gradient-to-br from-gray-50 to-gray-100">
        {imgUrl ? (
          <img
            src={imgUrl}
            alt={`Produto ${product.nome}`} 
            className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
            loading="lazy"
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center text-gray-400">
            <span className="text-sm font-medium">Sem imagem</span>
          </div>
        )}
        
        {product.variacoes && product.variacoes.length > 0 && (
          <div className="absolute top-3 left-3">
            <span className="bg-accent text-dark backdrop-blur-sm px-3 py-1.5 rounded-full text-xs font-bold shadow-md">
              {product.variacoes.length} {product.variacoes.length === 1 ? 'cor' : 'cores'}
            </span>
          </div>
        )}

        {product.destaque && (
          <div className="absolute top-3 right-3">
            <span className="bg-primary text-white backdrop-blur-sm px-3 py-1.5 rounded-full text-xs font-bold shadow-md">
              Destaque
            </span>
          </div>
        )}
      </div>

      <div className="p-5">
        <h3 className="font-title font-bold text-lg mb-2 line-clamp-2 min-h-[56px] text-dark group-hover:text-primary transition-colors">
          {product.nome}
        </h3>
        <p className="text-sm text-gray-500 font-medium mb-4">Código: {product.id}</p>

        <div className="flex gap-2">
          <button 
            onClick={onView} 
            className="flex-1 flex items-center justify-center gap-2 bg-gray-100 hover:bg-gray-200 text-dark font-semibold py-3 px-4 rounded-xl text-sm transition-all duration-200"
            aria-label={`Ver detalhes de ${product.nome}`}
          >
            <Eye size={16} />
            Detalhes
          </button>
        </div>
      </div>
    </article>
  )
})
